Add support for fp16 in convnet_benchmarks.py
caffe2/caffe2 pull request #1069
Opened 2017-08-10 06:05 UTC by sh1r0

2017-08-15 22:20 UTC, harouwu requested changes
Nice code! fp16 is super useful as an example of Caffe2. one major change request is to use`brew.arg_scope` to make code cleaner. Please check out caffe2.ai tutorial section: brewing your model. And PR #1093 is also a good example. 👍

2017-08-15 22:20 UTC, harouwu commented on caffe2/python/convnet_benchmarks.py
> +                WeightInitializer=initializer,
Nice use of Initializer. But I think you can use `arg_scope` in `brew` module to make the whole code cleaner. PR #1093 is a good example of it.

2017-08-15 22:20 UTC, harouwu commented on caffe2/python/convnet_benchmarks.py
> +    if use_fp16:
Do you think it is possible to refactor all of these Loss part so that our model building function can be dtype unaware?

2017-08-18 10:24 UTC, sh1r0 commented
@harouwu I've updated the commit for `arg_scope`, for the 2nd comment, I think it would be nice if `LabelCrossEntropy`, `Softmax`, etc. operations could be dtype aware (probably implicit dtype conversion).

2018-09-27 15:34 UTC, orionr commented
Thank you for your contribution! PyTorch and Caffe2 are now officially merged with the PyTorch 1.0 preview release. Please submit on https://github.com/pytorch/pytorch if this is still an issue over there.

2018-09-27 15:34 UTC, closed without merging