Use protobuf's own cmake scripts and add travis for ios
caffe2/caffe2 pull request #110
Opened 2017-01-27 17:26 UTC by Yangqing

2017-01-27 20:44 UTC, bwasti requested changes

2017-01-27 20:44 UTC, bwasti commented on cmake/ProtoBuf.cmake
> +  add_subdirectory(${CMAKE_SOURCE_DIR}/third_party/protobuf/cmake)
${PROJECT_SOURCE_DIR}

2017-01-27 20:44 UTC, bwasti commented on cmake/ProtoBuf.cmake
> +  include_directories(SYSTEM ${CMAKE_SOURCE_DIR}/third_party/protobuf/src)
ibid.

2017-01-28 04:38 UTC, Yangqing commented on scripts/build_host_protoc.sh
> +CAFFE2_ROOT="$( cd "$(dirname "$0")"/.. ; pwd -P)"
done

2017-01-28 04:38 UTC, Yangqing commented on cmake/ProtoBuf.cmake
> +  add_subdirectory(${CMAKE_SOURCE_DIR}/third_party/protobuf/cmake)
done

2017-01-28 04:38 UTC, Yangqing commented on cmake/ProtoBuf.cmake
> +  include_directories(SYSTEM ${CMAKE_SOURCE_DIR}/third_party/protobuf/src)
done

2017-01-28 21:29 UTC, closed without merging