Add random input scaling
caffe2/caffe2 pull request #1106
Opened 2017-08-17 12:24 UTC by slayton58

Add ability to specify a range for randomly scaling to a new shortest side. For example, for Resnet50 training, one would set `random_scale=[256,480]` in the `ImageInput` operator to resize to a random shortest side in the range [256, 480]

2017-08-17 21:46 UTC, harouwu reviewed
Only 2 incline comments. Travis CI test is a known issue. I would try to at least disable it today.

2017-08-17 21:46 UTC, harouwu commented on caffe2/image/image_input_op.h
> +    scale_to_use = std::uniform_int_distribution<>(256, 480)(*randgen);
Do you think we need to give people option to tune the scaled size? Or can we assume that all the image input will be scaled between 256 to 480?

2017-08-17 21:46 UTC, harouwu commented on caffe2/image/image_input_op.h
> +          OperatorBase::template GetRepeatedArgument<int>("random_scale", {-1,-1})) {
Perhaps adding instructions in the op doc will help people understand better why passing -1 as minimized scale will not be using random scaling.

2017-08-18 13:18 UTC, slayton58 commented on caffe2/image/image_input_op.h
> +    scale_to_use = std::uniform_int_distribution<>(256, 480)(*randgen);
Good point, this is incorrect - it should be taking the bounds from the `random_scale_` vector

2017-08-18 17:21 UTC, harouwu approved these changes
Landing this diff. Although I think we still need to add op schema for ImageInputOp

2017-08-18 17:29 UTC, harouwu requested changes
op level all looks good. But please add doc for the new arguments here: https://github.com/caffe2/caffe2/blob/master/caffe2/image/image_input_op.cc#L80

2017-08-18 18:51 UTC, closed without merging