Added local build and apple fix for generating .so files
caffe2/caffe2 pull request #147
Opened 2017-02-13 22:10 UTC by bwasti

2017-02-13 22:14 UTC, Yangqing commented
lgtm :)

2017-02-14 05:25 UTC, bwasti commented
broke builds :( I'll look into it

2017-02-14 05:54 UTC, Yangqing requested changes

2017-02-14 05:54 UTC, Yangqing commented on cmake/ProtoBuf.cmake
> +  if ( NOT Protobuf_FOUND )
@bwasti so this is the issue: in earlier versions of cmake (like 3.0.0) PROTOBUF_FOUND is used, and for some reason in the newest versions cmake started using Protobuf_FOUND, see:

https://github.com/Kitware/CMake/blob/v3.0.0/Modules/FindProtobuf.cmake

vs 

https://github.com/Kitware/CMake/blob/v3.7.2/Modules/FindProtobuf.cmake

and as a result, if we are only checking one, we end up missing the found message, ending up adding the custom protobuf find path.

I honestly think this is a cmake careless mistake, but I guess it means that we will need to guard both PROTOBUF_FOUND and Protobuf_FOUND. Maybe adding more message(WARNING "...") messages could help. My feeling is that the Protobuf package is not found, we are better off sending a warning message to the user saying "this is unusual, we will try to build with a local protobuf, but you should be noted that this path is flaky and you are better off installing your own protobuf and manually makes sure that c++ and python are using the same protobuf version".

2017-02-14 19:23 UTC, Yangqing commented
(btw, ignore the appveyor build fail right now, it is still WIP)

2017-02-16 14:11 UTC, closed without merging