Use prepare_input_override in derived RNNCells to rectify input_blob
caffe2/caffe2 pull request #2135
Opened 2018-03-05 20:53 UTC by pooyadavoodi

This helps with rectifying blobs. We don't need to worry about input_blob getting scoped in case it's a string rather than a BlobReference.

2018-03-19 01:30 UTC, salexspb commented
@pooyadavoodi , sorry for a delay. I am confused here. Does it matter if input to prepare_input is a string or not? if user implements custom prepare_input function, it is going to use either net. or brew. interface. In either case a string would be rectified automatically by Caffe2. 

The reason we had to rectify manually in _apply was that we introduced a new scope. But if user passes in a string we did not want that to get into a new scope before it is used. 

I don't understand how this is an issue for the prepare_input function. Also looks like for the MultiRNNCell it is also not an issue. 

Please correct me if I am wrong!

2018-03-19 01:30 UTC, salexspb requested changes
Please see my previous comment

2018-04-16 23:06 UTC, pooyadavoodi commented
@salexspb Sorry for the delay. I think I finally fixed the notification problem on my github account.

I think the problem was in MultiRNNCell, where we had to rectify the input: https://github.com/caffe2/caffe2/blob/master/caffe2/python/rnn_cell.py#L980

This occurs for example when `input_blob` of `rnn_cell._LSTM` is a string like here: https://github.com/caffe2/caffe2/blob/master/caffe2/python/rnn/rnn_cell_test_util.py#L54

2018-04-17 00:09 UTC, salexspb commented
I am confused. AddScopedExternalInputs doesn't return a string, it returns a ScopedBlobReference, not a string.

2018-04-18 02:03 UTC, pooyadavoodi commented
hmm, I see. I don't remember now why I added https://github.com/caffe2/caffe2/blob/master/caffe2/python/rnn_cell.py#L980

Let me go through my old tests. I will let you know.

2018-09-27 15:22 UTC, orionr commented
Thank you for your contribution! PyTorch and Caffe2 are now officially merged with the PyTorch 1.0 prerelease. Please submit on https://github.com/pytorch/pytorch if this is still an issue over there.

2018-09-27 15:22 UTC, closed without merging