Use Ninja build system when available
caffe2/caffe2 pull request #2160
Opened 2018-03-06 22:54 UTC by Maratyszcza

When Ninja is installed, use it instead of Make for native builds and for Android cross-builds.
Ninja is faster and generates less output in the terminal on successful builds.

2018-03-07 03:50 UTC, orionr approved these changes
LGTM

2018-03-07 03:58 UTC, Maratyszcza commented
@caffe2bot retest this please

2018-03-07 06:06 UTC, bddppq requested changes
setup.py needs to be changed as well

2018-03-07 13:23 UTC, Maratyszcza commented
@bddppq PTAL

2018-03-08 01:26 UTC, bddppq approved these changes
Looks good

2018-03-08 01:49 UTC, merged