Caffe2 Profiles
caffe2/caffe2 pull request #2269
Opened 2018-03-14 21:57 UTC by Maratyszcza

Enable dynamic modification of OperatorDef attributes based on platform or SoC name

2018-03-15 00:05 UTC, Maratyszcza commented
@caffe2bot retest this please

2018-03-15 16:23 UTC, yinghai commented on caffe2/core/profiles.cc
> +inline bool startsWith(
Move to `utils/string_utils.h`?

2018-03-15 22:03 UTC, Maratyszcza commented on caffe2/core/profiles.cc
> +inline bool startsWith(
Done!

2018-03-16 02:39 UTC, Maratyszcza commented
@caffe2bot retest this please

2018-03-18 21:00 UTC, Yangqing requested changes
I think in offline discussions folks are having quite nontrivial concerns about this design, so we probably want to iterate on this before landing. cc @salexspb @ajtulloch @bwasti .

2018-03-18 21:05 UTC, salexspb commented on caffe2/proto/caffe2.proto
> +  repeated Profile profile = 9;
I personally feel this is a hack. Protobufs are meant to be very rarely updated. The Predicate concept is very vaque. We will have to keep adding stuff there if we decide to go with protobuf changing approach. So I would discourage emulating predicates on the protobuf level. 

I wonder what are technical difficulties you see when you implement this without any changes to the protobuf. So far engines + runtime dispatch based on the available hardware worked. You just need to write dispatch logic on the library code level, but not on the serialization level. For example, check out perfkernels code, this is dispatch Dima and Yangqing added last year to support fast embedding lookup kernels from Misha.

2018-07-26 06:33 UTC, closed without merging