Add fp16 dispatch to main cuDNN operators
caffe2/caffe2 pull request #241
Opened 2017-04-03 15:55 UTC by slayton58

Adds support for fp16 to main cuDNN ops (conv, relu, pool, BatchNorm).

Done via. runtime dispatch, not using DispatchHelper at this point to allow for more complex dispatch logic in the future if necessary. Using separate template  for all input / output types is for these reasons also - it's easier to add the functionality now and never use it, than need to add it later.

2017-04-03 16:42 UTC, Yangqing commented
This is awesome, thanks @slayton58 !

(I am tagging a 0.6.0 version for pre-release but I am sure we will have it in by mid April.

2017-04-05 01:07 UTC, asaadaldien commented on caffe2/operators/conv_op_cudnn.cc
> +}
That breaks the build. add return true here.

2017-04-05 01:12 UTC, asaadaldien requested changes

2017-04-05 01:12 UTC, asaadaldien commented on caffe2/operators/conv_op_cudnn.cc
> +}
Please apply this to all Run** methods

2017-04-05 01:12 UTC, asaadaldien commented on caffe2/operators/relu_op_cudnn.cc
> +    // return (this->*body_)();
else LOG(FATAL) ? Also please return true at the end.

2017-04-05 12:56 UTC, slayton58 commented
@asaadaldien Done and updated

2017-04-05 20:20 UTC, asaadaldien requested changes
Looks good to me Thanks @slayton58 for working on this. few nits.

2017-04-05 20:20 UTC, asaadaldien commented on caffe2/operators/relu_op.cc
> +  auto& X = Input(0);
Remove unused variable X

2017-04-05 20:21 UTC, asaadaldien commented on caffe2/operators/conv_op_cudnn.cc
> +                         // float16,    // Math
Remove this line

2017-04-05 20:22 UTC, slayton58 commented on caffe2/operators/relu_op.cc
> +  auto& X = Input(0);
X is used. Strictly, Relu gradient requires X, Y, dY

2017-04-05 20:26 UTC, slayton58 commented on caffe2/operators/conv_op_cudnn.cc
> +                         // float16,    // Math
Done

2017-04-05 20:36 UTC, asaadaldien commented on caffe2/operators/relu_op.cc
> +  auto& X = Input(0);
Relu gradient needs only Y and dY also the variable X isn't  used in the code section bellow :)

2017-04-05 20:54 UTC, slayton58 commented on caffe2/operators/relu_op.cc
> +  auto& X = Input(0);
Ok, I'll be very explicit here. Relu gradient *should* be using X, the definition of it requires X. However, your CPU implementation doesn't, so I'll comment out this line, although it'll look weird starting with Input(1).

2017-04-06 02:41 UTC, ezineo commented on caffe2/operators/relu_op.cc
> +  auto& X = Input(0);
Sry, it's my fault. `Xvec` bellow actually means `dXvec`. Do you mind to fix it?

2017-04-11 19:30 UTC, closed without merging

2017-04-14 00:54 UTC, Yangqing commented
Simon, a quick question - this PR actually changes the signature of the ReluGradient function by *requiring* the input for the backward pass. In this case we won't be able to do in-place computation and old protos won't be able to run. Is it OK for us to revert to the old implementation where only the output is being provided for the backward pass? I think in any case, the relu backward pass should not need to use the input.

2017-04-14 00:57 UTC, Yangqing commented
@slayton58

2017-04-14 02:24 UTC, slayton58 commented
Sure - I originally added it as an error checking for cuDNN functions (as cudnnActivationBackwards takes X, Y, dY, but it doesn't seem to be 100% required

2017-04-14 16:25 UTC, Yangqing commented
Thanks @slayton58 for checking :) The fix is committed in https://github.com/caffe2/caffe2/commit/4a1713b833b9cd719b477bbea77d16b0c86a3fac and a unit test is in place to guard the numerical correctness.