Move setup.py and version into caffe2 folder.
caffe2/caffe2 pull request #2468
Opened 2018-03-28 17:32 UTC by orionr

* Prep for repository movement.

2018-03-28 17:38 UTC, pjh5 approved these changes

2018-03-28 19:35 UTC, bddppq requested changes
`find_packages` should also need changes

2018-03-28 19:35 UTC, bddppq commented on caffe2/setup.py
> +TOP_DIR = os.path.join(SRC_DIR, '..')
1. '..' is not truly cross-platform, there `os.pardir`
2. We should resolve the realpath instead of leaving `..` in it.

2018-03-28 19:36 UTC, bddppq commented
To test whether this will work, you should create a PR in onnx-fb-universe repo with `install.sh` modified and `repos/caffe2` points to this caffe2 PR's commit.

2018-03-28 21:53 UTC, orionr commented
Good catch on `find_packages()` - changing to `setuptools.find_packages(TOP_DIR)`

2018-03-28 22:36 UTC, orionr commented
Thanks @bddppq - universe PR up at https://github.com/onnxbot/onnx-fb-universe/pull/1358

2018-03-29 21:40 UTC, pjh5 approved these changes

2018-03-29 22:06 UTC, ezyang commented
Comments should call out that using absolute paths is important (relative paths don't work.) Does this work with `python setup.py develop`?

2018-03-30 15:13 UTC, orionr commented
We decided to rename instead - closing.

2018-03-30 15:13 UTC, closed without merging