Support fp16 output from ImageInputOp
caffe2/caffe2 pull request #400
Opened 2017-04-24 15:36 UTC by slayton58

Refactors out option -> datatype cast
Allows native fp16 output from GPU transformation path
Expanded CastOp to allow fp16 in/out on GPU

2017-04-25 17:42 UTC, asaadaldien requested changes
Looks good thanks @slayton58.
Just one comment :)

2017-04-25 17:42 UTC, asaadaldien commented on caffe2/image/transform_gpu.cu
> +bool TransformOnGPU<uint8_t, float16, CUDAContext>(Tensor<CUDAContext>& X, Tensor<CUDAContext> *Y, float std, float mean, CUDAContext *context)
The code is the same as above. What about moving the implementation to the templated version (line:45) ?

2017-04-25 18:40 UTC, slayton58 commented on caffe2/image/transform_gpu.cu
> +bool TransformOnGPU<uint8_t, float16, CUDAContext>(Tensor<CUDAContext>& X, Tensor<CUDAContext> *Y, float std, float mean, CUDAContext *context)
I swear there was a reason I didn't do that before, but I can't remember, and I fixed it this time, so it obviously wasn't too serious :)

Updated.

2017-04-25 22:57 UTC, asaadaldien requested changes

2017-04-25 22:57 UTC, asaadaldien commented on caffe2/image/image_input_op.h
> +  TensorProto_DataType output_type_;
Move this line bellow line:68 (breaks initialization order rule).

2017-04-26 01:09 UTC, slayton58 commented on caffe2/image/image_input_op.h
> +  TensorProto_DataType output_type_;
Done.

2017-04-28 21:50 UTC, closed without merging