Python3 compatibility (WIP)
caffe2/caffe2 pull request #526
Opened 2017-05-08 12:07 UTC by hgaiser

This PR is a first draft to get python2/3 compatibility in caffe2. Most noticeable changes come from the difference in `str` for python2 vs python3. python2 defines `bytes` and `str` as the same thing but in python3 they are two very different types.

Specifically the changes in `pybind_state` require some attention by caffe2 devs, as these are the areas where I am uncertain about the changes made.

Note that this PR is not finished, not all tests are running successfully in python3 yet and I have to test python2 again as well before this can be merged. I hope to continue work on this in a week or so, but meanwhile I was hoping to get some feedback on the changes made thus far.

ps. this PR depends on https://github.com/caffe2/caffe2/pull/463

2017-05-15 20:58 UTC, hgaiser commented
Did someone find the time to glance over this?

2017-05-15 21:19 UTC, lukeyeager requested changes
If you're picking a compatibility library, I suggest six because it's been around [longer](http://packages.ubuntu.com/search?keywords=python-six) than [future](http://packages.ubuntu.com/search?keywords=python-future) and because it does everything you need in one package instead of both `future` and `builtins`. But, I figure there are probably lots of compatibility libraries around, and you may know something I don't about some shortcoming of `six`.

2017-05-15 21:19 UTC, lukeyeager commented on caffe2/experiments/python/SparseTransformer.py
> +        for _, temp in cur.ops.items():
Using `six.iteritems()` would maintain the performance benefit in Py2. Not sure if the maintainers would want to add a new dependency, though.

2017-05-15 21:19 UTC, lukeyeager commented on caffe2/proto/caffe2.proto
> +  repeated bytes bytes = 9;
I'm pretty sure it's never OK to change these fields - only add new ones.

2017-05-15 21:19 UTC, lukeyeager commented on caffe2/python/mint/app.py
> +        trunc_size = data.shape[0] // step)
Syntax error, no?

2017-05-15 21:19 UTC, lukeyeager commented on caffe2/python/data_workers.py
> +from future import standard_library
NOTE: this is a new requirement

2017-05-15 21:19 UTC, lukeyeager commented on caffe2/python/operator_test/instance_norm_test.py
> +from builtins import zip
NOTE: this is a new requirement

2017-05-18 11:39 UTC, hgaiser commented on caffe2/experiments/python/SparseTransformer.py
> +        for _, temp in cur.ops.items():
I considered this, but felt that since it is only an experiment script it was not necessary to add a compatibility module here. Do you disagree?

2017-05-18 11:41 UTC, hgaiser commented on caffe2/proto/caffe2.proto
> +  repeated bytes bytes = 9;
Can you elaborate on this? The bytes field is now called `s`, which in my opinion should be used for string. I can move `optional string s = 4;` to the end to preserve order, but I would really prefer to rename `bytes s` to `bytes b`.

2017-05-18 11:41 UTC, hgaiser commented on caffe2/python/mint/app.py
> +        trunc_size = data.shape[0] // step)
Yes :) thanks.

2017-05-18 11:41 UTC, hgaiser commented on caffe2/python/data_workers.py
> +from future import standard_library
True, I'll add it in the comment of the PR.

2017-05-18 11:47 UTC, hgaiser commented
Thank you @lukeyeager for the review. Regarding the choice of `six` vs `future`, it seems the recommended approach is to use `future` unless you must support older versions of python (`future` supports python 2.6+ and 3.3+). According to their [FAQ](http://python-future.org/faq.html#what-is-the-relationship-between-future-and-six), `future` is more feature rich than `six`. The official [python page for porting](https://docs.python.org/3/howto/pyporting.html) also suggests to choose `future`.

What is your reason for preferring `six` over `future` ? Is it that `six` is already used in caffe2? Would it, given the above information, be desirable to port the small bits of `six` currently used to `future`, or would the preference be to stick with `six` ?

2017-05-18 15:11 UTC, lukeyeager commented on caffe2/experiments/python/SparseTransformer.py
> +        for _, temp in cur.ops.items():
Fair point. Not a big deal here.

2017-05-18 15:14 UTC, lukeyeager commented on caffe2/proto/caffe2.proto
> +  repeated bytes bytes = 9;
It's for backwards compatibility. If someone saves a trained model with one build of Caffe2, they should be able to load it in another build of Caffe2. See, for example, the hoops that the Caffe1 developers were constantly jumping through: https://github.com/BVLC/caffe/blob/rc5/src/caffe/proto/caffe.proto#L10-L22

Now, this only applies if we expect people to be saving to and loading from binary protocol buffers. If that's not an expected use-case, then it doesn't matter. Let's let the @caffe2 guys weigh in on this.

2017-05-18 15:15 UTC, lukeyeager commented
> What is your reason for preferring six over future ?

Good argument - you convinced me. I just hadn't heard about `future` before and was more familiar with `six`. Thanks for showing it to me!

2017-05-28 19:08 UTC, hgaiser commented
Rebased on master and fixed some issues as mentioned by @lukeyeager .

2017-05-28 21:17 UTC, hgaiser commented
This also seems to be largely obsolete after https://github.com/caffe2/caffe2/commit/6530c9a035682fbe94e882653ad624ca30c26c84 by @tomdz . I'll close this for now and open new PR(s) where necessary.

2017-05-28 21:17 UTC, closed without merging