Fix stats_ops_test
caffe2/caffe2 pull request #788
Opened 2017-06-12 23:35 UTC by lukeyeager

The global StatRegistry doesn't get reset when the workspace is reset.
```
>       self.assertTrue(len(workspace.FetchBlob('k3')) == 2)
E       AssertionError: False is not true
```
https://travis-ci.org/lukeyeager/caffe2/jobs/240162665

/cc @azzolini 

NOTE: this error doesn't show up if you just run `stats_ops_test.py` directly. It shows up when you run other tests in the same session before this test:
```
pytest -v caffe2/python/
```

2017-06-12 23:59 UTC, lukeyeager commented
In particular, try running these two tests:
```
pytest caffe2/python/checkpoint_test.py caffe2/python/operator_test/stats_ops_test.py
```

2017-06-14 18:31 UTC, salexspb requested changes

2017-06-14 18:31 UTC, salexspb commented on caffe2/python/operator_test/stats_ops_test.py
> +        keys = [__name__ + '/key1', __name__ + '/key2']
what if it is from the same file? Shouldn't this include the test name? You could also use line number.

2017-06-14 21:09 UTC, lukeyeager commented on caffe2/python/operator_test/stats_ops_test.py
> +        keys = [__name__ + '/key1', __name__ + '/key2']
Ok, updated.

2017-06-15 22:08 UTC, closed without merging