Change basename for proto tensor naming to avoid name collision
caffe2/caffe2 pull request #925
Opened 2017-07-12 15:43 UTC by danielhauagge

Changed the base string used to name parameter tensors to void name clashing. This would happen with in-place operators. This script originally used as the base name the layer's output. This strategy caused all layers that had the same output name (which happens for in-place operators) to have the same base parameter name, which in some cases caused name collisions.

More discussion on this issue [here](https://github.com/caffe2/caffe2/issues/468).

2017-07-12 15:53 UTC, danielhauagge commented
I just signed the CLA, not sure if the message from the facebook-github-bot will update automatically with that info or not.

2017-08-16 21:59 UTC, harouwu requested changes
Looks like we will have to change the name of ops that are using these outputs as its input.

2017-08-16 21:59 UTC, harouwu commented on caffe2/python/caffe_translator.py
> +    output = layer.name
Do you think we will also need to change the name of these blobs when they are used as inputs to other ops?

2017-08-16 23:11 UTC, danielhauagge commented on caffe2/python/caffe_translator.py
> +    output = layer.name
I tested this a bit and seemed to work fine. That said, I'm just starting with caffe2.

2018-09-27 15:34 UTC, orionr commented
Thank you for your contribution! PyTorch and Caffe2 are now officially merged with the PyTorch 1.0 preview release. Please submit on https://github.com/pytorch/pytorch if this is still an issue over there.

2018-09-27 15:34 UTC, closed without merging